name: flutter_web_client
description: A Flutter web client for managing the Christmas shopping list.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

flutter:
  uses-material-design: true
